### ISSUE TITLE
The steps in the README are in the wrong order

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/sinatra-basic-views-lab#5]
Hi. The README for this lab says that you need to "start by writing the HTML in index.erb", run the Rspec tests, and then write the corresponding controller action.

However, the tests have this in the reverse order. Even if you write the correct HTML, they all fail unless you write the controller action FIRST.

All you need to do is switch Step 1 and Step 2 in the README, and you're good.

Thanks (as always) for looking into this!

---Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
